[Seat:*]
xserver-command = X -nocursor
session-cleanup-script = pkill -P1 -fx /usr/sbin/lightdm
autologin-user = stepmania
autologin-session = xinit-compat
greeter-session = lightdm-autologin-greeter
