name: Build testing container image

on:
  push:
    branches:
      - beta

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate tag
        id: tag
        run: |
          echo "tag=beta-$(cat game_version)-${GITHUB_SHA::6}" >> ${GITHUB_OUTPUT}

      - name: test
        run: |
          echo "${{ steps.tag.outputs.tag }}"

      - name: Build bootc container image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: os
          tags: "beta ${{ steps.tag.outputs.tag }}"
          labels: |
            org.opencontainers.image.version="${{ steps.tag.outputs.tag }}"
          containerfiles: |
            ./Containerfile

      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/stepmania
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Test
        run: |
          echo "image: ${{ steps.build-image.outputs.image-with-tag }} image: ${{ steps.build-image.outputs.image }} tags: ${{ steps.build-image.outputs.tags }}"
